### ISSUE TITLE
We have 5 markers, could it possible to have 5 assessors in coursework module?

### ISSUE THREAD

**Issue by Lina-LI-Na** [ULCC/open-mod_coursework#10]
Dear developers,
This is not an issue. But I didn't find a platform which I can contact with you. So I posted this question here. If this is not a proper place to discuss this, would you please suggest a better communication way?

We love coursework module very much. Thank you for your great contributions.
In our University, we have 5 markers for the final year project. But currently, the coursework module only can set 3 assessors. Is that possible for me to change a configuration to make it able to do 5 assessors? Or if this need to change code, would you please help to develop this function?

Besides, I checked all the support documents and video, but didn't find the allocate upload template. Could you please tell me the template so that I can upload allocations manually?

Thanks and looking forward to your reply.
Best wishes,
Lina

**Comment by aferenz** [comment]
Hi Lina, 

Unfortunately coursework module only allows the maximum of 3 markers for one coursework and there is no configuration to increase it. In order to have more than 3 assessors, significant changes to the code would need to be made. Drop me a line (a.ferenz@ulcc.ac.uk) and I will send you a template for assessor allocation upload. 

Aleks

**Comment by Lina-LI-Na** [comment]
Hi Aleks,
Thank you for your kind reply. I've sent you email for the template.
Thanks.
Lina

**Comment by aferenz** [comment]
Hi Lina, 

I have replied to your email.

Regards,
Aleks
